import type { GeneratedChange, TestRunResult, ReviewSummary, RunOutcome } from '../workbench.types.js';

const STATUS_MARK: Record<RunOutcome, string> = {
  Passed: '✅ passed',
  Failed: '❌ failed',
  Flaky: '⚠️ flaky',
  Skipped: '⏭️ skipped',
  'Needs approval': '⏳ needs approval',
};

/**
 * Builds a reviewer-friendly PR description from the workbench session: a run summary, the tests added
 * (each tagged with its run status), and an issues section (failing/flaky/skipped tests with their
 * reason, file, and any likely cause / suggested fix). Pure data → markdown.
 */
export function buildPullRequestBody(input: {
  changes: GeneratedChange[];
  run?: TestRunResult;
  review?: ReviewSummary;
}): string {
  const { changes, run, review } = input;
  const statusByTitle = new Map((run?.matrix ?? []).map(row => [row.title, row.status]));
  const lines: string[] = ['Generated by Guardrail.', ''];

  if (review) {
    lines.push('## Test run summary');
    lines.push('');
    lines.push(`- Passing: **${review.testsPassing}**`);
    lines.push(`- Added: ${review.testsAdded} · Updated: ${review.testsUpdated} · Deleted: ${review.testsDeleted}`);
    if (review.flakyTracked) lines.push(`- Flaky tracked: ${review.flakyTracked}`);
    lines.push('');
  }

  lines.push('## Tests added');
  lines.push('');
  for (const change of changes) {
    const status = statusByTitle.get(change.title);
    const tag = status ? ` — ${STATUS_MARK[status]}` : '';
    lines.push(`- \`${change.file}\` — ${change.title}${tag}`);
  }
  lines.push('');

  const issues = buildIssues(run, review);
  if (issues.length) {
    lines.push('## Issues to resolve');
    lines.push('');
    lines.push('> These behaviors did not pass. The expected behavior is encoded in the test — fix the');
    lines.push('> application code (not the test) so the behavior holds, then re-run Guardrail to verify.');
    lines.push('');
    for (const issue of issues) {
      lines.push(`### ${issue.mark} ${issue.title}`);
      lines.push(`- **Test file:** \`${issue.file}\``);
      lines.push(`- **Detail:** ${issue.reason}`);
      if (issue.likelyCause) lines.push(`- **Likely cause:** ${issue.likelyCause}`);
      if (issue.suggestedFix) lines.push(`- **Suggested fix:** ${issue.suggestedFix}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

function buildIssues(run: TestRunResult | undefined, review: ReviewSummary | undefined) {
  const detailByTitle = new Map((review?.failures ?? []).map(failure => [failure.title, failure]));
  const rows = (run?.matrix ?? []).filter(row => row.status === 'Failed' || row.status === 'Flaky' || row.status === 'Skipped');

  if (rows.length) {
    return rows.map(row => {
      const detail = detailByTitle.get(row.title);
      return {
        title: row.title,
        mark: STATUS_MARK[row.status],
        reason: row.reason ?? detail?.reason ?? 'No detail captured.',
        file: row.file,
        likelyCause: detail?.likelyCause,
        suggestedFix: detail?.suggestedFix,
      };
    });
  }

  return (review?.failures ?? []).map(failure => ({
    title: failure.title,
    mark: failure.kind === 'flaky' ? STATUS_MARK.Flaky : STATUS_MARK.Failed,
    reason: failure.reason,
    file: failure.file,
    likelyCause: failure.likelyCause,
    suggestedFix: failure.suggestedFix,
  }));
}
